# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apidoc < Formula
  desc "RESTful API 文档生成工具"
  homepage "https://github.com/caixw/apidoc"
  version "7.2.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/caixw/apidoc/releases/download/v7.2.2/apidoc_7.2.2_macOS_amd64.tar.gz"
    sha256 "373079587819327c9cd99852e8ceb80832a76d77e6d44dbaaa3c772843fe4838"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/caixw/apidoc/releases/download/v7.2.2/apidoc_7.2.2_macOS_arm64.tar.gz"
    sha256 "0a3d94f30446009aec782b7c7eab79680519668c249b88ea2eeb40143940c08b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caixw/apidoc/releases/download/v7.2.2/apidoc_7.2.2_linux_amd64.tar.gz"
    sha256 "dcfd53f3ca40227779494461dd1eaa2dc5514f54acd392fe227df41c18ae37a1"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/caixw/apidoc/releases/download/v7.2.2/apidoc_7.2.2_linux_arm64.tar.gz"
    sha256 "0f86a01eaa7eb1d4364b3c91c1b0575481daec42dc5fdab33a2e6dd055d174c1"
  end

  def install
    bin.install "apidoc"
  end
end
