# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blogit < Formula
  desc "静态博客生成工具"
  homepage "https://github.com/caixw/blogit"
  version "1.5.3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/caixw/blogit/releases/download/v1.5.3/blogit_1.5.3_macOS_amd64.tar.gz"
    sha256 "5e2664364f9d86dc78715166ca6fa47f0560673baee090de626edb89ef3fd439"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/caixw/blogit/releases/download/v1.5.3/blogit_1.5.3_macOS_arm64.tar.gz"
    sha256 "87b6c56f47fe2137a670f86a5a73d26aebf2bbff173f72808767c608699e12e4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caixw/blogit/releases/download/v1.5.3/blogit_1.5.3_linux_amd64.tar.gz"
    sha256 "c0be6ac7dfbc53e9c60c3c1ae3f36456f77523dadcb12362f9797783afa2093a"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/caixw/blogit/releases/download/v1.5.3/blogit_1.5.3_linux_arm64.tar.gz"
    sha256 "9776439527a782f2b92a46b515e56d97e50c9590429ca5e32a668034c36e8296"
  end

  def install
    bin.install "blogit"
  end
end
