# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blogit < Formula
  desc "静态博客生成工具"
  homepage "https://github.com/caixw/blogit"
  version "2.0.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caixw/blogit/releases/download/v2.0.0/blogit_2.0.0_macOS_amd64.tar.gz"
      sha256 "f12f684a27f788d9e34f0ca87402570715167c03b205961f71cc2630293f152b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/caixw/blogit/releases/download/v2.0.0/blogit_2.0.0_macOS_arm64.tar.gz"
      sha256 "d80eb2898d3367f25e0fadb639e19261743c56d1ce2c53c3d4a330ea09d26178"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caixw/blogit/releases/download/v2.0.0/blogit_2.0.0_linux_amd64.tar.gz"
      sha256 "1c3523ddaee0b4c9b5f27521d8fb0caeaa3b53996012846443637dd5a35b4f66"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caixw/blogit/releases/download/v2.0.0/blogit_2.0.0_linux_arm64.tar.gz"
      sha256 "7ce7f2e74463c69172c2240389dea6b106ea88707bdf125dc3ab2c7356cc62b9"
    end
  end

  def install
    bin.install "blogit"
  end
end
