# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobuild < Formula
  desc "Go 热编译工具"
  homepage "https://github.com/caixw/gobuild"
  version "1.8.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/caixw/gobuild/releases/download/v1.8.3/gobuild_1.8.3_darwin_amd64.tar.gz"
      sha256 "85037402aa6adeb1eaee13f55e65452ed48cd2b18e3d05b6bd63fc2d5212e9e4"

      def install
        bin.install "gobuild"
      end
    end
    on_arm do
      url "https://github.com/caixw/gobuild/releases/download/v1.8.3/gobuild_1.8.3_darwin_arm64.tar.gz"
      sha256 "140c09497acedc53a15b23e799f9c87dbda0999157ef52f75e60923637573a87"

      def install
        bin.install "gobuild"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caixw/gobuild/releases/download/v1.8.3/gobuild_1.8.3_linux_amd64.tar.gz"
        sha256 "b5ec7b2213238400f377779f531de20630df0c701efe701dcba4e2c4fe522d30"

        def install
          bin.install "gobuild"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caixw/gobuild/releases/download/v1.8.3/gobuild_1.8.3_linux_arm64.tar.gz"
        sha256 "8554c49807f4e702117b72f888a0263476e1808b5b1b7ed3c7d21a6776631314"

        def install
          bin.install "gobuild"
        end
      end
    end
  end
end
