# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Web < Formula
  desc "框架 web 的辅助工具"
  homepage "https://github.com/issue9/web"
  version "0.93.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/issue9/web/releases/download/v0.93.2/web_0.93.2_darwin_amd64.tar.gz"
      sha256 "e4e995f51d30ac874df65809458209a7593f6a60e73d19b9be836eebc64b2228"

      def install
        bin.install "web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/issue9/web/releases/download/v0.93.2/web_0.93.2_darwin_arm64.tar.gz"
      sha256 "aa8b6b9900e68b0ce0067ae25c6a07a50b4e0b086ad989448b80a27048ca1528"

      def install
        bin.install "web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/issue9/web/releases/download/v0.93.2/web_0.93.2_linux_amd64.tar.gz"
      sha256 "4419833b0b8ca1f0701f7a2d2ea276bffc0c5e761705bb4a8bfa5f3616359dcb"

      def install
        bin.install "web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/issue9/web/releases/download/v0.93.2/web_0.93.2_linux_arm64.tar.gz"
      sha256 "9b56714fe1c8c20c5609e29afffaa0960d85358c886ee39d13fc13a1ab137bea"

      def install
        bin.install "web"
      end
    end
  end
end
