# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Web < Formula
  desc "框架 web 的辅助工具"
  homepage "https://github.com/issue9/web"
  version "0.102.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/issue9/web/releases/download/v0.102.6/web_0.102.6_darwin_amd64.tar.gz"
      sha256 "727b441917f04545046c02c91ece860779a30ce30d5dcd28064691e7195e944e"

      def install
        bin.install "web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/issue9/web/releases/download/v0.102.6/web_0.102.6_darwin_arm64.tar.gz"
      sha256 "1a7409b84c1b8da66dd5e506bbb692f5f7e1cffd2dc9cafaf41bdb622405ecb6"

      def install
        bin.install "web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/issue9/web/releases/download/v0.102.6/web_0.102.6_linux_amd64.tar.gz"
        sha256 "1be64c0d4899edaf03f57409f8c5b4bf9f9246fba4d0fffb21930e6e5c910019"

        def install
          bin.install "web"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/issue9/web/releases/download/v0.102.6/web_0.102.6_linux_arm64.tar.gz"
        sha256 "d2a762ed42813714ad776d281c2a09290ea600f57eeaa198121ea2382c87d2ce"

        def install
          bin.install "web"
        end
      end
    end
  end
end
