# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Web < Formula
  desc "框架 web 的辅助工具"
  homepage "https://github.com/issue9/web"
  version "0.104.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/issue9/web/releases/download/v0.104.5/web_0.104.5_darwin_amd64.tar.gz"
      sha256 "0939e15b914321ad755f1f85d1eca66f55a0683407b7988fa3ae4f87420156a9"

      define_method(:install) do
        bin.install "web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/issue9/web/releases/download/v0.104.5/web_0.104.5_darwin_arm64.tar.gz"
      sha256 "39115265cbb98098eae2a5302dd314e5049dc8f3485065f696870016e6be0bed"

      define_method(:install) do
        bin.install "web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/issue9/web/releases/download/v0.104.5/web_0.104.5_linux_amd64.tar.gz"
      sha256 "b5b46f7d572bfe29de814133cfcb0ad00c194225ca946904141454194512c889"
      define_method(:install) do
        bin.install "web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/issue9/web/releases/download/v0.104.5/web_0.104.5_linux_arm64.tar.gz"
      sha256 "e1c9dcb3e38b0c9bbe7cb682496583cf5071b463379aa440b41ba260777c0222"
      define_method(:install) do
        bin.install "web"
      end
    end
  end
end
